---
abstract: 'Perl module filesystem partition identification.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FileSystem-Partition
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.06
  Error::Pure: 0.17
  Text::CSV: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=FileSystem-Partition
  homepage: https://github.com/tupinek/FileSystem-Partition
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/FileSystem-Partition
version: '0.01'
